server:
  port: 9191

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
      - id: LOGIN-SERVICE
        uri: lb://LOGIN-SERVICE
        predicates:
          - Path=/olx/login/**
      - id: ADVERTISE-SERVICE
        uri: lb://ADVERTISE-SERVICE
        predicates:
          - Path=/olx/advertise/**
      - id: MASTER-SERVICE
        uri: lb://MASTER-SERVICE
        predicates:
          - Path=/olx/advertise/**
          
  zipkin:
   base-url: http://localhost:9411

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}    